"""empty message

Revision ID: 0149ad5e844c
Revises: c3aa3d9c6383
Create Date: 2021-05-08 13:32:11.945500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0149ad5e844c'
down_revision = 'c3aa3d9c6383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('avg_num_medical_terms', sa.Float(), nullable=True))
    op.drop_column('dataset', 'num_medical_terms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('num_medical_terms', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('dataset', 'avg_num_medical_terms')
    # ### end Alembic commands ###
