"""empty message

Revision ID: 99135526c465
Revises: 3b84fe4459c9
Create Date: 2021-05-08 13:49:32.112430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99135526c465'
down_revision = '3b84fe4459c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('avg_word_count', sa.Float(), nullable=True))
    op.drop_column('dataset', 'avg_length')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('avg_length', mysql.FLOAT(), nullable=True))
    op.drop_column('dataset', 'avg_word_count')
    # ### end Alembic commands ###
