"""empty message

Revision ID: c3aa3d9c6383
Revises: 
Create Date: 2021-05-08 09:44:54.558368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3aa3d9c6383'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avg_length', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('sentence_count', sa.Integer(), nullable=True),
    sa.Column('num_medical_terms', sa.Integer(), nullable=True),
    sa.Column('most_common_words', sa.String(length=2000), nullable=True),
    sa.Column('avg_sentence_length', sa.Float(), nullable=True),
    sa.Column('avg_sentence_variance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_data',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('one_line_summary', sa.Text(), nullable=True),
    sa.Column('one_paragraph_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_data')
    op.drop_table('dataset')
    # ### end Alembic commands ###
